apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vifleqrtd-python 
  janus-idp.io/tekton: vifleqrtd-python
  backstage.io/kubernetes-id: vifleqrtd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vifleqrtd-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  